---
title: "p8105_hw6_mgg2153"
author: "mggn"
date: "12/8/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)
```

### Problem 2

```{r load_data}

bwt_df = 
  read_csv("./data/birthweight.csv") %>%
  janitor::clean_names() %>%
  mutate(
    mrace = as.factor(mrace),
    frace = as.factor(frace),
    babysex = as.factor(babysex),
    malform = as.factor(malform)
  )

sapply(bwt_df, function(x) sum(is.na(x))) #looks like there are no missing values, let's build a model
```
```{r my_model}

#model based on information from my thesis, give justification later :D

mg_model = lm(bwt ~ gaweeks+mrace+ppbmi, data = bwt_df)

mg_model %>% broom::tidy()

bwt_df %>%
  modelr::add_predictions(mg_model) %>%
  modelr::add_residuals(mg_model) %>%
  ggplot(aes(x = resid, y = pred))+geom_point()+#look back at regression notes :D
  geom_smooth(se = FALSE, method = "lm", color = "green")+
  theme_bw()+
  labs(
    x = "Residuals",
    y = "Predicted values",
    title = "Residuals vs. predicted values", #yhat?
    caption = "Regression diagnostics"
  )


```
#### Model comparisons, cross-validation using modelr


```{r regression}

#main effects model

main_effect = lm(bwt ~ blength + gaweeks, data = bwt_df)

main_effect %>% broom::tidy()


```

```{r}

#head circumference, length, sex, and all interactions
saturated = lm(bwt ~ bhead*blength*babysex, data = bwt_df)

saturated %>% broom::tidy()

```

```{r}

cv_df =
  crossv_mc(bwt_df, 100)

cv_df = 
cv_df %>%
  mutate(
    mg_model = map(train, ~lm(bwt ~ gaweeks+mrace+ppbmi, data = .x)),
    main_effect = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    saturated = map(train, ~lm(bwt ~ bhead*blength*babysex, data = .x))
  ) %>%
  mutate(
    rmse_mg_model = map2_dbl(mg_model, test, ~rmse(model = .x, data = .y)),
    rmse_main_effect = map2_dbl(main_effect, test, ~rmse(model = .x, data = .y)),
    rmse_saturated = map2_dbl(saturated, test, ~rmse(model = .x, data = .y))
  )

```

Look at distribution of RMSEs

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_boxplot(aes(fill=model))+
  theme_bw()

```


### Problem 3

Wow this looks like a fun one

```{r load_noaa}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

set.seed(1)

```

```{r}
weather_df %>%
  bootstrap(n = 5000)%>%
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)
  ) %>%
  select(-strap, -models) %>%
  unnest(results) %>%
  group_by(term) %>%
  janitor::clean_names()%>%
  pivot_wider(
    names_from = "term",
    values_from = "estimate"
  )%>%
  janitor::clean_names()
```



